### ISSUE TITLE
Click attribute error on commons CLI

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#129]
Here is how to reproduce the bug.
```
pipenv run python -m soweego commons
```
yields
```py
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/focs/soweego/soweego/__main__.py", line 3, in <module>
    cli.cli(obj={})
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 1086, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 516, in get_help
    return self.command.get_help(self)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 879, in get_help
    self.format_help(ctx, formatter)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 898, in format_help
    self.format_options(ctx, formatter)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 1017, in format_options
    self.format_commands(ctx, formatter)
  File "/Users/focs/.local/share/virtualenvs/soweego-jENbvpMi/lib/python3.7/site-packages/click/core.py", line 1066, in format_commands
    if cmd.hidden:
AttributeError: 'function' object has no attribute 'hidden'
<class 'AttributeError'>
```

**Comment by MaxFrax** [comment]
@marfox I cannot reproduce the bug. It works on my machine.
I tried also on docker and it works in there, too.

Are you still able to reproduce it?

**Comment by marfox** [comment]
@MaxFrax , it's working from my side as well. At the time of opening this issue, we must have forgot some CLI command declaration. Closing.
